visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: "http://localhost"

train:
  lr: 0.001

  batch_size: 64
  number_of_processes: 4

  save:
    model: '../data/weights/ae/'
    every: 10

  load: True

  base_model_weights: '../data/weights/mnist/model-70.trh'

validation:
  use_validation: True
