visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: 'http://localhost'

train:
  lr: 0.001

  batch_size: 64
  number_of_processes: 4

  save:
    model: '../data/weights/cifar10/ae/'
    every: 1

  load: True

  base_model_weights: '../data/weights/cifar10/model-30.trh'
  ae_model_weights: '../data/weights/cifar10/ae/model-8.trh'

  image:
    every: 10

validation:
  use_validation: True
