visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: "http://localhost"

train:
  lr: 0.001

  batch_size: 512
  number_of_processes: 4

  save:
    model: '../data/weights/cifar10/'
    every: 10

  load: False

validation:
  use_validation: True
