visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: "http://localhost"

train:
  lr: 0.001

  batch_size: 128
  number_of_processes: 4

  dataset_path: '../data/kannada_mnist/train.csv'

  save:
    model: '../data/weights/kannada_mnist/'
    every: 10

  load: False

validation:
  use_validation: True
