visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: "http://localhost"

train:
  lr: 0.01
  
  batch_size: 128
  number_of_processes: 4

  save:
    model: '../data/weights/mnist/'
    every: 10

  load: False

validation:
  use_validation: True
