visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: 'http://localhost'

train:
  data: '../data/datasets/nist19/'

  lr: 0.001

  batch_size: 128
  number_of_processes: 4

  save:
    model: '../data/weights/nist19_2/ae_2/'
    every: 10

  load: True

  base_model_weights: '../data/weights/nist19_2/model-3.trh'
  ae_model_weights: '../data/weights/nist19_2/ae_2/model-60.trh'

  image:
    every: 10

validation:
  use_validation: True
