visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: "http://localhost"

train:
  data: '../../HandwrittenCharacterGenerator/data/'

  lr: 0.001

  batch_size: 64
  number_of_processes: 4

  save:
    model: '../data/weights/nist19_2/'
    every: 20

  load: False

validation:
  use_validation: True
