visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: 'http://localhost'

train:
  data: '../data/datasets/nist19/'
  permutation: '../data/datasets/nist19/nist19_permutation.npy'

  lr: 0.01

  batch_size: 64
  number_of_processes: 4

  save:
    model: '../data/weights/nist19_2/vae_2/'
    every: 100

  load: True

  base_model_weights: '../data/weights/nist19/model-4.trh'
  ae_model_weights: '../data/weights/nist19_2/ae_2/model-60.trh'

  image:
    every: 10

validation:
  use_validation: True
