visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: "http://localhost"

train:
  data: '../data/datasets/nist19/'

  lr: 0.001

  batch_size: 256
  number_of_processes: 4

  save:
    model: '../data/weights/nist19/'
    every: 1

  load: False

validation:
  use_validation: True
